object Versions {
    const val kotlinVersion = "1.5.21"
    const val kotlinxSerialization = "1.2.1"

    // Google Libs
    const val palette = "1.0.0"
    const val constraintLayout = "2.1.4"
    const val androidxAnnotation = "1.1.0"
    const val androidxBrowser = "1.2.0"
    const val androidMaterial = "1.3.0"
    const val supportLibraryLayout = "1.0.0"
    const val legacyV4 = "1.0.0"
    const val multidex = "2.0.1"
    const val coreLibDesugaring = "1.0.9"
    const val recyclerView = "1.1.0"
    const val swipeRefreshLayoutVersion = "1.1.0"
    const val coroutinesVersion = "1.5.1"
    const val coroutinesLifecycleScopeVersion = "2.5.1"

    const val appcompat = "1.2.0"
    const val lifecycle = "2.3.1"
    const val coreKtx = "1.3.1"
    const val androidxActivityVersion = "1.2.1"
    const val androidxLocalBroadcastVersion = "1.0.0"
    const val androidxBiometric = "1.1.0-rc01"
    const val flexbox = "2.0.1"
    const val preference = "1.1.1"
    const val startup = "1.1.0"

    const val glideVersion = "4.11.0"
    const val glideTransformationVersion = "4.1.0"

    const val retrofitVersion = "2.6.4"
    const val retrofitKSerializationConverterVersion = "0.8.0"
    const val okHttpVersion = "3.12.12"
    const val okHttpLoggingVersion = "3.12.0"
    const val gsonVersion = "2.8.6"

    const val koinVersion = "2.2.3"

    const val archNavigation = "2.3.4"

    // Test Libs
    const val espressoVersion = "3.4.0"
    const val espressoVersionDown = "3.3.0"
    const val assertJVersion = "3.20.2"
    const val hamcrestVersion = "1.3"
    const val mockitoVersion = "2.2.0"
    const val benchmark = "1.0.0"
    const val mockWebserverVersion = "3.12.8"
    const val androidTestVersion = "1.3.0"
    const val androidCoreVersion = "2.1.0"
    const val junitTest = "4.13"
    const val trust = "1.1.2"
    const val coreTesting = "2.1.0"
    const val junit5Test = "5.8.2"
    const val testExtJunit = "1.1.3"
    const val rx2Idler = "0.11.0"
    const val testMonitor = "1.4.0"
    const val mockitoKotlin = "3.2.0"
    const val mockito = "3.3.3"
    const val jsonAndroid = "20190722"
    const val fragment = "1.5.3"
    const val faker = "1.2.8"
    const val robolectricVersion = "4.6.1"
    const val reflectionsVersion = "0.9.12"
    const val coreTest = "1.3.0"
    const val turbine = "0.5.2"
    const val mockk = "1.12.0"
    const val mockkAndroid = "1.12.0"
    const val byteBuddyAndroidVersion = "1.10.14"
    const val detekt = "1.21.0"
    const val lint = "30.0.2"
}